all:
	clang++ -O3 tcp_tic_tac_toe.cpp -o tictactoe.out

console:
	clang++ -O3 console_tic_tac_toe.cpp -o console.out

tcp:
	clang++ -O3 tcp_tic_tac_toe.cpp -o tictactoe.out

.PHONY : clean
clean : 
	rm -f *.out
