all:
	clang++ -O3 tcp_tic_tac_toe.cpp -o tictactoe.out
	clang++ -O3 webserver_tic_tac_toe.cpp -o webserver_tictactoe.out

console:
	clang++ -O3 console_tic_tac_toe.cpp -o console.out

tcp:
	clang++ -O3 tcp_tic_tac_toe.cpp -o tictactoe.out

web:
	clang++ -O3 webserver_tic_tac_toe.cpp -o webserver_tictactoe.out

.PHONY : clean
clean : 
	rm -f *.out
	rm -f *.gch
